### ISSUE TITLE
Thumbnail not generated and cannot be uploaded

### ISSUE THREAD

**Issue by mofetdanielsmolkin** [open-lms-open-source/moodle-mod_mediagallery#25]
Hello, 

We Have and issue with this mod/plugin. (we use MOODLE 3.10)

when are uploading mp4 video and selecting (default) "use as thumbnail" in the item settings screen.
those specific settings ignored during save process and therefore no thumbnail created / shown

I've tried to debug the issue my self, and i couldn't find something that could pin point the issue.

could you please explain what am i doing wrong or there is a bug?

please find picture of the setting/s attached.

Thanks in advance
![Screenshot 2022-02-06 101713](https://user-images.githubusercontent.com/78465711/152673004-eac97705-41ed-430e-9fab-524a50623430.png)

Daniel,

**Comment by aolley** [comment]
So currently, the custom thumbnail only works when the gallery focus setting is set to something that is _not_ "image".

Otherwise, the custom thumbnail is completely disregarded as you say.

Looking over the history of the project - I can't really see a particular reason why this was the case.

So I reckon we can have the thumbnail selector work despite the focus setting - and also show the generated thumbnail for any images when you edit them later.

**Comment by aolley** [comment]
This is taken care of in 23936962d00d616f1eca885ee4779406e2d6c479
A new release will go out soon to include that.

**Comment by mofetdanielsmolkin** [comment]
hello, 
Thanks a lot for your quick response, 
waiting for the official release :)
